# scrape.sub

executable              = run_script.sh
arguments               = $(input_file) $(output_file)

log                     = logs/run_$(Cluster)_$(Process).log
output                  = logs/run_$(Cluster)_$(Process).out
error                   = logs/run_$(Cluster)_$(Process).err
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT

request_cpus            = 1
request_memory          = 1028M
request_disk            = 1G

queue input_file, output_file from arg.txt
